### ISSUE TITLE
Single vs. double dashes in flags

### ISSUE THREAD

**Issue by tomoneill19** [freakyclown/flag_standard#1]
The irony isn't lost on me that I'm creating a post to debate a standard in a standards setting document, but all the same I think the point of this sort of project would be to discuss amongst the community and get the standard "right" the once so it's consistent across things.
In my view, -help is probably wrong compared to --help.
I'd suggest this because I think single dash is for single letter flags and that they can generally be chained i.e. `-a -b -c` could also be written as `-abc` or `-a -cb` etc) and they should all be acceptable commands.
-? or -h seems prefectly reasonable for help (personally I prefer -h) but double dashes is a solid standard for full words or phrases because it allows for `--multi-word-flag` with a starting double and following singles.
Interested to know views on this.

**Comment by Duck3y** [comment]
I'd have to agree that the use of double dashes for full or multi-word flags is correct, with single dashes being used for individual letters or group of letters (say 3 maximum).

**Comment by freakyclown** [comment]
Updated and merged.
